# Generated by Django 4.2.10 on 2024-02-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AircraftID', models.CharField(max_length=100)),
                ('EquipmentType', models.CharField(max_length=100)),
                ('TypeCode', models.CharField(max_length=100)),
                ('Year', models.CharField(max_length=100)),
                ('Make', models.CharField(max_length=100)),
                ('Model', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Class', models.CharField(max_length=100)),
                ('GearType', models.CharField(max_length=100)),
                ('EngineType', models.CharField(max_length=100)),
                ('Complex', models.CharField(max_length=100)),
                ('HighPerformance', models.CharField(max_length=100)),
                ('Pressurized', models.CharField(max_length=100)),
                ('TAA', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=100)),
                ('FlightID', models.CharField(max_length=100)),
                ('From', models.CharField(max_length=100)),
                ('To', models.CharField(max_length=100)),
                ('Route', models.CharField(max_length=100)),
                ('TimeOut', models.CharField(max_length=100)),
                ('TimeOff', models.CharField(max_length=100)),
                ('TimeOn', models.CharField(max_length=100)),
                ('Timein', models.CharField(max_length=100)),
                ('OnDuty', models.CharField(max_length=100)),
                ('OffDuty', models.CharField(max_length=100)),
                ('TotalTime', models.CharField(max_length=100)),
                ('minPICUS', models.CharField(max_length=100)),
                ('SIC', models.CharField(max_length=100)),
                ('inNight', models.CharField(max_length=100)),
                ('Solo', models.CharField(max_length=100)),
                ('CrossCountry', models.CharField(max_length=100)),
            ],
        ),
    ]
